{{ config(
    materialized='table'
) }}

SELECT
  MATCH_ID,
  CITY,
  DATES_1 AS MATCH_DATE,
  EVENT_NAME,
  MATCH_NUMBER,
  MATCH_TYPE,
  MATCH_TYPE_NUMBER,
  GENDER,
  VENUE,
  TOSS_WINNER,
  TOSS_DECISION,
  WINNER,
  MATCH_RESULT,
  BY_INNINGS,
  BY_WICKETS,
  BY_RUNS,
  PLAYER_OF_MATCH_ID,
  SEASON,
  TEAM_1,
  TEAM_2
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}
WHERE MATCH_ID IS NOT NULL
