{{ config(
    materialized='table'
) }}

SELECT DISTINCT
  UMPIRE_1_ID AS UMPIRE_ID,
  UMPIRE_1 AS UMPIRE_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  UMPIRE_2_ID AS UMPIRE_ID,
  UMPIRE_2 AS UMPIRE_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TV_UMPIRES_ID AS UMPIRE_ID,
  TV_UMPIRES AS UMPIRE_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  RESERVE_UMPIRES_ID AS UMPIRE_ID,
  RESERVE_UMPIRES AS UMPIRE_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  MATCH_REFEREES_ID AS UMPIRE_ID,
  MATCH_REFEREES AS UMPIRE_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}



