{{ config(
    materialized='table'
) }}

SELECT DISTINCT
  PLAYER_OF_MATCH_ID AS PLAYER_ID,
  PLAYER_OF_MATCH AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}
WHERE PLAYER_OF_MATCH_ID IS NOT NULL

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_1_ID AS PLAYER_ID,
  TEAM_1_PLAYER_1 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_2_ID AS PLAYER_ID,
  TEAM_1_PLAYER_2 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_3_ID AS PLAYER_ID,
  TEAM_1_PLAYER_3 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_4_ID AS PLAYER_ID,
  TEAM_1_PLAYER_4 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_5_ID AS PLAYER_ID,
  TEAM_1_PLAYER_5 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_6_ID AS PLAYER_ID,
  TEAM_1_PLAYER_6 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_7_ID AS PLAYER_ID,
  TEAM_1_PLAYER_7 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_8_ID AS PLAYER_ID,
  TEAM_1_PLAYER_8 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_9_ID AS PLAYER_ID,
  TEAM_1_PLAYER_9 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_10_ID AS PLAYER_ID,
  TEAM_1_PLAYER_10 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_11_ID AS PLAYER_ID,
  TEAM_1_PLAYER_11 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_1_PLAYER_12_ID AS PLAYER_ID,
  TEAM_1_PLAYER_12 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_1_ID AS PLAYER_ID,
  TEAM_2_PLAYER_1 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_2_ID AS PLAYER_ID,
  TEAM_2_PLAYER_2 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_3_ID AS PLAYER_ID,
  TEAM_2_PLAYER_3 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_4_ID AS PLAYER_ID,
  TEAM_2_PLAYER_4 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_5_ID AS PLAYER_ID,
  TEAM_2_PLAYER_5 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_6_ID AS PLAYER_ID,
  TEAM_2_PLAYER_6 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_7_ID AS PLAYER_ID,
  TEAM_2_PLAYER_7 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_8_ID AS PLAYER_ID,
  TEAM_2_PLAYER_8 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_9_ID AS PLAYER_ID,
  TEAM_2_PLAYER_9 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_10_ID AS PLAYER_ID,
  TEAM_2_PLAYER_10 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_11_ID AS PLAYER_ID,
  TEAM_2_PLAYER_11 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}

UNION

SELECT DISTINCT
  TEAM_2_PLAYER_12_ID AS PLAYER_ID,
  TEAM_2_PLAYER_12 AS PLAYER_NAME
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}




