{{ config(
    materialized='table'
) }}

SELECT
  SEASON,
  BATTER,
  SUM(RUNS_BATTER) AS TOTAL_RUNS
FROM {{ source('raw', 'ALL_IPL_MATCH_DATA') }}
GROUP BY SEASON, BATTER
QUALIFY RANK() OVER (PARTITION BY SEASON ORDER BY SUM(RUNS_BATTER) DESC) <= 10
